name: Ask 4 Join
description: Register your Ship
title: "Ask 4 join"
labels: []
projects: []
assignees: []
body:
  - type: input
    id: github_email
    attributes:
      label: Github Email
      description: We Need the Email to Contact you
      value: "your.name@example.com"
    validations:
      required: true
  - type: input
    id: dns
    attributes:
      label: DNS Record
      description: Where should the domain point to? You can type in either an IP address or a domain, and it will automatically detect whether to use A, AAAA, or CNAME.
    validations:
      required: true
  - type: checkboxes
    id: checked
    attributes:
      label: Agreement
      options:
        - label: im Sure to Join
          required: true
