name: Ask 4 Join
description: Register your Ship
title: "Ask 4 join"
labels: []
projects: []
assignees: []
body:
  - type: input
    id: github_email
    attributes:
      label: Github Email
      description: We Need the Email to Contact you
      value: "your.name@example.com"
    validations:
      required: true
  - type: input
    id: dctag
    attributes:
      label: Discord Tag
      description: Discord Tag to Invite you to the Development Server
    validations:
      required: true
  - type: checkboxes
    id: checked
    attributes:
      label: Agreement
      options:
        - label: im Sure to Join
          required: true
